### ISSUE TITLE
Auto-waiting assertions

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright-runner#41]
It would be nice to have auto-wait assertions like those in expect-playwright baked in.

https://github.com/playwright-community/expect-playwright

```
await expect(page).toHaveSelector("#foobar")
await expect(page).toHaveText("#my-element", "MyValue")
```

**Comment by JoelEinbinder** [comment]
I had a conversation with @mxschmitt about this offline. Pasting my parts here:

There are a lot of thought provoking ideas in that library, but I am having trouble coming up with a response that covers all of them.

I think we should discuss them individually.
Some should be built into playwright-runner, some into playwright itself, some stay in external libraries.

Like the first example:
```js
await expect(page).toHaveSelector("#foobar");
```
This is pretty much equivalent to `await page.waitForSelector('#foobar')` right?

but then
```js
await expect(page).not.toHaveSelector("#foobar");
```
makes everything a lot trickier

because is this
```js
expect(await page.$('#foobar')).toBe(null);
```
or is it
```js
expect(await page.waitForSelector('#foobar').catch(e => null)).toBe(null);
```

one will always wait the full timeout, making the test slow

The other will pass if the element comes in later. So you could have both
`expect(page).toHaveSelector` and `expect(page).not.toHaveSelector` pass!

I don't think the "`not`" case is very important, but staying within the expect syntax forces us to implement it. What if instead it was in playwright itself as a collection of page.assert methods? Then it would also be clearer that expect is synchronous and page.assert is async.

**Comment by jperl** [comment]
Yes `page.assert` methods would serve the same purpose as `expect`, I do not have a strong opinion either way about this.

I can think of a few scenarios where `.not.toHaveSelector` and `.not.toHaveText` are valuable. 

- After [marking items as complete]([items as complete](http://todomvc.com/examples/react), to make sure they are gone
- After dismissing a modal, to make sure it is gone

In both of those I would want the test to auto-wait for the selector to be gone. So the test should only be as slow as the application is to remove those elements.

**Comment by thernstig** [comment]
The text one would be cool to have. An example would be `expect(page/element).toHaveText('some text')`, taking into account somehow the 3 different kind of text matchers `text=example one` (case-insensitive, substring matching), `text="example 2"` (exact matching), `text=/^\\s*Some text$/i` (regex matching).

Also, I assume the `.not.toHaveText('some text')` would equal to use `waitForSelector('text=some text', {waitFor: 'hidden'})`
