### ISSUE TITLE
setup/teardown

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright-runner#9]
We should have hooks for setting up some test servers or other long running processes when the test run starts and shutting them down when the test run ends. I believe jest already has apis for this, but its a question of integrating with them.

**Comment by mxschmitt** [comment]
We had a discussion going on about forking [jest-dev-server](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server) and rewriting it since its not maintained anymore actively.

It would be cool to have especially with device / browser enumeration a way of executing commands before and after for e.g. setting up a database and cleaning it up afterwards.

Additional to that it would be nice to have jest-dev-server functionality, either integrated or providing support for it so we could start e.g. a backend or the frontend with it.

**Comment by mxschmitt** [comment]
Probably it does not make much sense to use jest-dev-server there. I thought about the following:
- startup/teardown hooks in the playwright.config
- startup/teardown hooks if you test multiple browsers
- There you can basically implement your own customisable async function to use e.g. that: https://www.npmjs.com/package/wait-on or execute shell commands (maybe provide a small helper for that)
